### ISSUE TITLE
Change icon size using css

### ISSUE THREAD

**Issue by erqk** [avmaisak/ngx-bootstrap-icons#182]
I've been using version 1.2x before, and I can style icon size directly in css using 'font-size', but not now when I using the latest version. Is it intended or a bug? I'm missing the feature that can style directly in css.

**Comment by erqk** [comment]
Ok I found out the value of the width and height in SVG is different, perhaps the update of bootstrap icons caused this changes. Previous one is using "em" and now just number.

**Comment by avmaisak** [comment]
@erqk I will try to check and fix it as soon as possible

**Comment by avmaisak** [comment]
@erqk i will add a boolean input - resetDefaultDimensions - if this parameter is set, default dimensions of the svg icon will be removed. I hope, this feature will help you/

**Comment by erqk** [comment]
> @erqk i will add a boolean input - resetDefaultDimensions - if this parameter is set, default dimensions of the svg icon will be removed. I hope, this feature will help you/

Thanks! That will be a great convenient for people like me who like to style using css!

**Comment by erqk** [comment]
> > @erqk i will add a boolean input - resetDefaultDimensions - if this parameter is set, default dimensions of the svg icon will be removed. I hope, this feature will help you/
> 
> Thanks! That will be a great convenient for people like me who like to style using css!

I found that after the dimension is removed, the icon will become very big and I still cannot style the size using font-size attribute. Seems like the only way is to using "em" or "rem" unit in the svg dimension. Is it possible to convert the default size of 16 to 1em like previous?

**Comment by avmaisak** [comment]
> > > @erqk i will add a boolean input - resetDefaultDimensions - if this parameter is set, default dimensions of the svg icon will be removed. I hope, this feature will help you/
> > 
> > 
> > Thanks! That will be a great convenient for people like me who like to style using css!
> 
> I found that after the dimension is removed, the icon will become very big and I still cannot style the size using font-size attribute. Seems like the only way is to using "em" unit in the svg dimension. Is it possible to convert the default size of "16" to "1em" like previous?

@erqk  - you cannot set resetDefaultDimensions=true and set globaly in css your's default icon dimensions?

**Comment by erqk** [comment]
![image](https://user-images.githubusercontent.com/64851043/105438525-17463f80-5c9e-11eb-9afd-41c47beb17df.png)
This is not working when the dimensions are removed. Neither width/height or font-size is working.
![image](https://user-images.githubusercontent.com/64851043/105438659-62f8e900-5c9e-11eb-8b4d-0652fbdf4d88.png)
But when dimension is set using "em", it works using font-size.

**Comment by avmaisak** [comment]
@erqk sorry for waiting, please, create new issue with this problem.
