### ISSUE TITLE
Icon dimension cannot be set property with css font-size

### ISSUE THREAD

**Issue by erqk** [avmaisak/ngx-bootstrap-icons#222]
![image](https://user-images.githubusercontent.com/64851043/105438816-aeab9280-5c9e-11eb-9fe8-8db9760da3ea.png)
This is not working when the dimensions are removed. Neither width/height or font-size is working.

![image](https://user-images.githubusercontent.com/64851043/105438659-62f8e900-5c9e-11eb-8b4d-0652fbdf4d88.png)
But when dimension is set using "em", it works using font-size.

And I've checked out the official bootstrap icon library, all of their icons have the dimensions of "16" without any unit. So if it's impossible/too many works to make it using "1em", then I will just style them directly in HTML.

_Originally posted by @erqk in https://github.com/avmaisak/ngx-bootstrap-icons/issues/182#issuecomment-765074792_

**Comment by avmaisak** [comment]
@erqk ,

I can propose this solution. 

I want to add configure options for module.So, you can assign default preffered dimensions, and then, you can manipulate with dimensions in css, how you need,

```ts  

NgxBootstrapIconsModule.forRoot(icons, { 
    width: '2em', 
    height: '2em', 
    theme: ColorTheme.Danger,
})

```

**Comment by avmaisak** [comment]
@erqk i tested it. and it works as expected, 
@erqk  there will be additional wishes?

**Comment by avmaisak** [comment]
@erqk please, look at https://github.com/avmaisak/ngx-bootstrap-icons/pull/228

**Comment by erqk** [comment]
> @erqk i tested it. and it works as expected,
> @erqk there will be additional wishes?

Wow, so that will be great! So far I'm very satisfy with your work, no more additional wishes.😀
