### ISSUE TITLE
How to use these icons in CSS?

### ISSUE THREAD

**Issue by ayoubkhan558** [avmaisak/ngx-bootstrap-icons#269]
How to use these icons in CSS?

**Comment by avmaisak** [comment]
hello, @ayoubkhan558 .
this library does not envisage working with icons in css.

Please, see usage of this library
https://github.com/avmaisak/ngx-bootstrap-icons/blob/develop/README.md

**Comment by ayoubkhan558** [comment]
Why, I think it should work in CSS

**Comment by avmaisak** [comment]
> Why, I think it should work in CSS

@ayoubkhan558 

You can use component like this, by adding needed css class and etc.

`
<i-bs name="bootstrap"
                width="2rem"
                height="2rem"
                class="text-white"></i-bs>
`
