### ISSUE TITLE
Commonjs Warning

### ISSUE THREAD

**Issue by tayambamwanza** [avmaisak/ngx-bootstrap-icons#289]
Angular is warning me that the library is using commonjs, I don't know if it will be possible to use esm instead, I haven't narrowed down the problem either but I thought I'd make an issue about it, I can look into it for you if you want, in terms of how much work it might take.

```console
Warning: /home/tayamba/Repositories/web-app-merchants/apps/template-app/client/src/app/app.module.ts depends on 'ngx-bootstrap-icons'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by tayambamwanza** [comment]
https://ncjamieson.com/bundling-cjs-as-esm/, I'll check out this article when I've got the time.

**Comment by avmaisak** [comment]
Hello, @tayambamwanza .

at the moment i use `"module": "esnext"` in `compilerOptions`. In demo application, there are no warnings like you commented.

**Comment by tayambamwanza** [comment]
Hi, I'll close this issue, I don't know what happened, the warning is gone now :)
