### ISSUE TITLE
Replace lodash with lodash-es or lodash.camelcase to make angular compiler happy & builds smaller

### ISSUE THREAD

**Issue by BadlyDrewn** [avmaisak/ngx-bootstrap-icons#357]
I think this is the only place it's used.

https://github.com/avmaisak/ngx-bootstrap-icons/blob/d0132fafe2a11566923f1f90d478c61438ab989a/projects/ngx-bootstrap-icons-lib/src/lib/components/ngx-bootstrap-icons/ngx-bootstrap-icons.component.ts#L4

replacing it with

```ts
import * as camelCase from 'lodash.camelcase';
```

And updating the peer dependancies package.json would make ng build happy & build size smaller

**Comment by avmaisak** [comment]
fixed at 1.4.5

**Comment by avmaisak** [comment]
@BadlyDrewn in next release, a will remove this dependency too. So, i wrote function toCamelCase and added in to internal space of the library. If it interested, please, see develop branch

**Comment by avmaisak** [comment]
@BadlyDrewn , please  remove this dependency , and update to1.4.6

**Comment by BadlyDrewn** [comment]
Fantastic - thanks for your work
