### ISSUE TITLE
ES-Lint conflicts

### ISSUE THREAD

**Issue by tayambamwanza** [avmaisak/ngx-bootstrap-icons#53]
Hi, I'm getting a lot of conflicts/red lines from eslint rules that are not really being used, and so can be removed.

e.g. for private variables, eslint says they must have a leading _

e.g. it complains about

```ts
  constructor(private icons: object) { }
```
and basically wants

```ts
  constructor(private _icons: object) { }
```

**Comment by tayambamwanza** [comment]
How did you setup this es-lint? was it manually or using ng add @angular-eslint/schematics ?

**Comment by avmaisak** [comment]
@tayambamwanza i'm using my custom eslint config based on [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript#airbnb-javascript-style-guide-) with my own modifications. 

This eslint rules is not required, but i want to use it and fix all issues in project codebase

**Comment by avmaisak** [comment]
@tayambamwanza i created issue ( #54 ) to track fix eslint errors progress

**Comment by tayambamwanza** [comment]
Ok, so I should leave this open?
