### ISSUE TITLE
Support for Icon and Theme Types

### ISSUE THREAD

**Issue by tayambamwanza** [avmaisak/ngx-bootstrap-icons#540]
This is for an optional feature that can be supported because of Angulars 'fullTemplateTypeCheck' mode, which provides enhanced autocomplete features for type safety in the html templates.

Earlier I submitted an issue for using optional Enums, which were helpful in narrowing down what options where available and avoiding typos, the downside is that one would have to import the enums and assign them to a variable to make use of them

i.e

```ts
iconEnums = IconEnums
```

My proposal is to add support for a custom IconName Type 

i.e

```ts
export type IconName
```

and allow it as an optional input type.

The benefit will be that the user will not need to import and assign anything anymore, angular language service should autocomplete from a list of specified strings if fullTemplateTypeCheck is enabled.

By adding this feature as an option, current users will not need to do any migration work.

I am willing to do the pull request for this.

**Comment by avmaisak** [comment]
@tayambamwanza it will be great! I will bi waitng for PR

**Comment by tayambamwanza** [comment]
#541
