### ISSUE TITLE
Picking individual icons vs importing allIcons makes no difference in bundle size

### ISSUE THREAD

**Issue by ovidiucp** [avmaisak/ngx-bootstrap-icons#645]
I was trying to understand why the size of the generated bundle is so big, so I ran the `webpack-bundle-analyzer` tool on a project that looks like this.

```
import { NgxBootstrapIconsModule, allIcons } from 'ngx-bootstrap-icons';
import { arrowDown } from 'ngx-bootstrap-icons';

const icons = {
    arrowDown,
};

@NgModule({
    declarations: [
        ...
    ],
    imports: [
        ...
        NgxBootstrapIconsModule.pick(icons),
        ...
    ],
})
export class AppModule {
}
```

To run the bundle analyzer, I ran the following in my project's directory:

```
npm install --save-dev webpack-bundle-analyzer
ng build --stats-json
node_modules/.bin/webpack-bundle-analyzer dist/labeler/stats.json
```

This opens a browser window showing the sizes of the various modules in my app. The size of the `ngx-bootstrap-icons.js` is the same whether I `pick(icons)` or I import `allIcons` and then `pick(allIcons)`, and is 1.23MB parsed size.

This happens on Angular 12.

Any thoughts on what's going on?

**Comment by avmaisak** [comment]
@ovidiucp thank you for question. Please, could you provide your's full code example? May be you still use this module in another modules?

**Comment by ovidiucp** [comment]
Here's the setup.

```
ng new angular12
npm i ngx-bootstrap-icons --save
npm install --save-dev webpack-bundle-analyzer
```

app.module.ts:

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { NgxBootstrapIconsModule, arrowDown } from 'ngx-bootstrap-icons';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

const icons = {
    arrowDown,
};

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        AppRoutingModule,
        NgxBootstrapIconsModule.pick(icons),
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

app.component.ts:

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular12';
}
```

app.component.html:

```
<p>
  <i-bs name="arrow-down"></i-bs>
  App component
</p>
```

Verify the works by running `ng serve`.  Then run:

```
ng build --stats-json
node_modules/.bin/webpack-bundle-analyzer dist/angular12/stats.json
```

In the web page that is shown by the bundle analyzer hover over ngx-bootstrap-icons.js and look at the size. The parsed size is 1.3MB, and is as big as Angular itself whose parsed size 1.31MB.

Then modify the code to include `allIcons` instead of just `arrowDown`. Run the build analyzer again and you'll notice the same size for the `ngx-bootstrap-icons`.

**Comment by ovidiucp** [comment]
**Update**: Looks like the size reported by `webpack-bundle-analyzer` is not indicative of what ends up in the generated bundle.

I ran `ng build --prod` on both versions of the code. The one with just one icon is 222KB, the one with all the icons is 999KB.

My bad, all seems good, sorry for wasting your time!

**Comment by avmaisak** [comment]
@ovidiucp , that's ok, you're welcome )
