### ISSUE TITLE
Demo search not working on Firefox

### ISSUE THREAD

**Issue by Dafnik** [avmaisak/ngx-bootstrap-icons#673]
Hi everyone,

I noticed that the demo search isn't working on Firefox.

I'm running `Firefox 94.0` and it seems like it's working on Chrome-based browsers.

**Comment by avmaisak** [comment]
@Dafnik  - you try search localy or via https://avmaisak.github.io/ngx-bootstrap-icons ?

 - in text box type words and press enter

**Comment by Dafnik** [comment]
Thanks for the quick fix!

**Comment by avmaisak** [comment]
@Dafnik please contact if you have any questions!
