### ISSUE TITLE
Bootstrap Icons v1.10.0

### ISSUE THREAD

**Issue by bduncan137** [avmaisak/ngx-bootstrap-icons#848]
Wondering if there are any plans to update to include the new icons released in v1.10.0 https://blog.getbootstrap.com//2022/11/11/bootstrap-icons-1-10-0/ . Btw, great project, thanks!

**Comment by avmaisak** [comment]
@bduncan137 , yes, i want to update lib as soon as possible

**Comment by bduncan137** [comment]
thanks again!
